   # This is a basic workflow to help you get started with Actions

name: Synchronize JSON data from Airtable base

       # Controls when the workflow will run
on:
  # Triggers the workflow every day
  schedule:
    - cron: "1 2 * * *"
  workflow_dispatch:

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TABLES: ${{ secrets.TABLES }}
      G_TOKEN: ${{ github.token }} # see https://github.com/settings/tokens/new
      G_REPO: ${{ secrets.G_REPO }}
      G_OWNER: ${{ secrets.G_OWNER }}
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }} # see https://airtable.com/account
      AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      FILENAME: ${{ secrets.FILENAME }}  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: jeffrummel/airtable-importer@v1.1
        with:
          node-version: 16
      - run: npm ci
      - run: node index.js
      