name: 'Airtable Importer'
description: 'Pull data from an Airtable base and convert it to JSON.'

# Controls when the workflow will run
on:
  # Triggers the workflow every day
  schedule:
    - cron: "1 2 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TABLES: impactbase
      G_TOKEN: ${{ github.token }} # see https://github.com/settings/tokens/new
      G_REPO: ${{ secrets.G_REPO }}
      G_OWNER: ${{ secrets.G_OWNER }}
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }} # see https://airtable.com/account
      AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      FILENAME: ${{ secrets.G_FILENAME }}  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: jeffrummel/airtable-importer
        with:
          node-version: 16
      - run: npm ci
      - run: node index.js
      